### ISSUE TITLE
Loader issue

### ISSUE THREAD

**Issue by pruthvishetty** [hwchase17/chat-langchain#21]
I'm trying to replicate the steps here 'https://github.com/hwchase17/chat-langchain' and while running `ingest.sh`, I get the following error: `No module named 'langchain.document_loaders'`. Any ideas on how best to resolve this would be appreciated. Thanks in advance!

**Comment by rajpoojary** [comment]
I had a similar issue, I fixed this error by explicitly specifying newer version of langchain in requirements.txt

**Comment by pruthvishetty** [comment]
Fixed.

**Comment by rebol016** [comment]
> y explicitly specifying n

hello, how can I explicitly specify newer version of langchain， thx in advance
