### ISSUE TITLE
Trying to run ingest.sh but receive illegal option

### ISSUE THREAD

**Issue by jccbbb** [hwchase17/chat-langchain#48]
When I try to run the ingest.sh does it output the following error:
`./ingest.sh: 4: set: Illegal option -`

Have I misunderstood the instructions? I have run `pip install -r requirements.txt` before trying to execute the .sh file 😊

**Comment by bigsky77** [comment]
Make sure your API key is set in the env by running.  

`export OPENAI_API_KEY=....`

You do not need to run ingest.sh directly.  You can run 'python ingest.py' and then 'make start'.  Also you may need to reformat ingest_doc() to use unstructucturedURLLoader().

**Comment by jccbbb** [comment]
> Make sure your API key is set in the env by running.
> 
> `export OPENAI_API_KEY=....`
> 
> You do not need to run ingest.sh directly. You can run `python ingest.py` and then `make start`. Also you may need to reformat ingest_doc() to use unstructucturedURLLoader().

Thank you this solved my problem 😊

**Comment by joaocarlosleme** [comment]
> unstructucturedURLLoader(

Didn´t find anything on the documentation regarding "unstructucturedURLLoader". Running the code on ingest_doc() does require to run ingest.sh since ReadTheDocsLoader looks for the documents on the local folder directory that is created by ingest.sh.

**Comment by joaocarlosleme** [comment]
> > Make sure your API key is set in the env by running.
> > `export OPENAI_API_KEY=....`
> > You do not need to run ingest.sh directly. You can run `python ingest.py` and then `make start`. Also you may need to reformat ingest_doc() to use unstructucturedURLLoader().
> 
> Thank you this solved my problem 😊

TTBOMK what you did simply got away with the error (solved the problem) by loading NOTHING since you do must run ingest.sh to download the content of the website into a local folder that is latter loaded using ingest.py.
