### ISSUE TITLE
aget_relevant_documents() got an unexpected keyword argument 'callbacks'

### ISSUE THREAD

**Issue by UladzimirLaziuk** [hwchase17/chat-langchain#96]
hello
sender='you' message='hello' type='stream'
ERROR:root:aget_relevant_documents() got an unexpected keyword argument 'callbacks'

**Comment by UladzimirLaziuk** [comment]
sorry

**Comment by UladzimirLaziuk** [comment]
sorry async def aget_relevant_documents(self, query: str, **kwargs) -> List[Document]:
    return self.get_relevant_documents(query, **kwargs)

VectorStoreRetriever.aget_relevant_documents = aget_relevant_documents

**Comment by DishanthHM** [comment]
Why is this closed ?

**Comment by UladzimirLaziuk** [comment]
Hello.
adding kwargs solved everything)
async def aget_relevant_documents(self, query: str, **kwargs) ->
List[Document]: return self.get_relevant_documents(query, **kwargs)

ср, 5 июл. 2023 г. в 10:04, Dishanth H M ***@***.***>:
